export const data = [
  {
    questao: "Qual é o principal objetivo de ter zero defeitos nos produtos?",
    imagem: "imgs\\questao1_transparente.svg",
    opcoes: [
      "A) Reduzir custos",
      "B) Aumentar a produção",
      "C) Satisfazer o cliente corretamente",
      "D) Minimizar os materiais utilizados",
    ],
    resposta: 2,
  },
  {
    questao: "O que significa o princípio de 'Satisfação do Cliente'?",
    imagem: "imgs\\questao2.svg",
    opcoes: [
      "A) Fazer os produtos mais rápidos",
      "B) Atender e exceder as expectativas do cliente",
      "C) Produzir em maior quantidade",
      "D) Reduzir custos de produção",
    ],
    resposta: 1,
  },
  {
    questao: "Como as reclamações dos clientes são tratadas na empresa?",
    imagem: "imgs\\questao3.svg",
    opcoes: [
      "A) São ignoradas",
      "B) São passadas para outra equipe",
      "C) São visualizadas e resolvidas diretamente na área de trabalho",
      "D) São resolvidas apenas uma vez por mês",
    ],
    resposta: 2,
  },
  {
    questao: "O que é o 'Stop Sign' e por que ele é usado?",
    imagem: "imgs\\questao4_transparente.svg",
    opcoes: [
      "A) Para indicar um problema de qualidade e interromper a produção",
      "B) Para chamar um supervisor",
      "C) Para reduzir o tempo de produção",
      "D) Para aumentar a velocidade de fabricação",
    ],
    resposta: 0,
  },
  {
    questao: "Quem decide encerrar um 'Stop Sign'?",
    imagem: "imgs\\questao5.svg",
    opcoes: [
      "A) Operador da linha",
      "B) Gestores de manufatura e logística",
      "C) Clientes",
      "D) Supervisores de vendas",
    ],
    resposta: 1,
  },
  {
    questao:
      "O que um colaborador deve fazer ao notar um problema de qualidade?",
    imagem: "imgs\\questao6.svg",
    opcoes: [
      "A) Ignorar o problema",
      "B) Notificar e parar o processo, se necessário",
      "C) Resolver sozinho e continuar",
      "D) Aguardar o gerente resolver",
    ],
    resposta: 1,
  },
  {
    questao: "O que significa 'Reação Rápida' em casos de problemas?",
    imagem: "imgs\\questao7.svg",
    opcoes: [
      "A) Reagir ao final do turno",
      "B) Aguardar por uma solução",
      "C) Resolver imediatamente com ações rápidas",
      "D) Ignorar problemas menores",
    ],
    resposta: 2,
  },
  {
    questao: "Como o operador pode parar o processo se vir algo errado?",
    imagem: "imgs\\questao8.svg",
    opcoes: [
      "A) Chamando o gerente",
      "B) Continuando o processo",
      "C) Utilizando o sistema de 'Andon' ou cordão de parada",
      "D) Esperando até o final do turno",
    ],
    resposta: 2,
  },
  {
    questao: "Por que a organização e limpeza (5S) são importantes?",
    imagem: "imgs\\questao9.svg",
    opcoes: [
      "A) Reduzem o tempo de limpeza",
      "B) Melhoram a organização e segurança",
      "C) Ajudam a cumprir metas de produção",
      "D) São apenas regras de segurança",
    ],
    resposta: 1,
  },
  {
    questao: "Por que é importante ter instruções claras no local de trabalho?",
    imagem: "imgs\\questao10.svg",
    opcoes: [
      "A) Para os colaboradores não errarem",
      "B) Para evitar retrabalho",
      "C) Para ter processos eficientes e evitar erros",
      "D) Para reduzir o tempo de produção",
    ],
    resposta: 2,
  },
  {
    questao: "O que é uma FMEA e para que ela serve?",
    imagem: "imgs\\questao11.svg",
    opcoes: [
      "A) Para melhorar o visual dos produtos",
      "B) Para ajudar a evitar possíveis falhas",
      "C) Para acelerar o processo de produção",
      "D) Para aumentar a produtividade",
    ],
    resposta: 1,
  },
  {
    questao: "Como os processos são controlados para manter a qualidade?",
    imagem: "imgs\\questao12.svg",
    opcoes: [
      "A) Através de verificações e padrões de controle",
      "B) Aumentando a quantidade de produtos",
      "C) Diminuindo os materiais utilizados",
      "D) Reduzindo o número de verificações",
    ],
    resposta: 0,
  },
  {
    questao: "Por que monitorar os equipamentos de medição?",
    imagem: "imgs\\questao13.svg",
    opcoes: [
      "A) Para aumentar a produção",
      "B) Para garantir precisão nas medições",
      "C) Para reduzir o tempo de trabalho",
      "D) Para evitar manutenções regulares",
    ],
    resposta: 1,
  },
  {
    questao: "O que deve ser verificado nos equipamentos de medição?",
    imagem: "imgs\\questao14.svg",
    opcoes: [
      "A) Se estão devidamente calibrados",
      "B) Se são modernos",
      "C) Se possuem peças sobressalentes",
      "D) Se têm boa aparência",
    ],
    resposta: 0,
  },
  {
    questao: "Como garantir que os equipamentos estejam funcionando bem?",
    imagem: "imgs\\questao15.svg",
    opcoes: [
      "A) Verificando regularmente a calibração",
      "B) Mudando de equipamentos frequentemente",
      "C) Ignorando problemas pequenos",
      "D) Usando apenas uma vez ao dia",
    ],
    resposta: 0,
  },
  {
    questao: "O que o princípio 'Check the Checker' quer dizer?",
    imagem: "imgs\\questao16.svg",
    opcoes: [
      "A) Garantir a qualidade dos equipamentos de inspeção",
      "B) Verificar o operador",
      "C) Revisar as metas de produção",
      "D) Inspecionar o gerente",
    ],
    resposta: 0,
  },
  {
    questao: "Por que se usam câmeras e sensores para controle de qualidade?",
    imagem: "imgs\\questao17.svg",
    opcoes: [
      "A) Para reduzir o tempo de produção",
      "B) Para detectar falhas e melhorar a precisão",
      "C) Para diminuir o número de funcionários",
      "D) Para facilitar a supervisão",
    ],
    resposta: 1,
  },
  {
    questao: "O que é o sistema 'Poka Yoke'?",
    imagem: "imgs\\questao18.svg",
    opcoes: [
      "A) Um método para prevenir falhas humanas",
      "B) Um sistema de aumento de produção",
      "C) Uma técnica para treinar funcionários",
      "D) Uma forma de eliminar custos",
    ],
    resposta: 0,
  },
  {
    questao: "Qual é a importância de manter as máquinas em bom estado?",
    imagem: "imgs\\questao19.svg",
    opcoes: [
      "A) Garantir a continuidade e a qualidade da produção",
      "B) Aumentar o número de peças produzidas",
      "C) Reduzir o uso de energia",
      "D) Melhorar a aparência da fábrica",
    ],
    resposta: 0,
  },
  {
    questao: "O que é a TPM (Manutenção Produtiva Total)?",
    imagem: "imgs\\questao20.svg",
    opcoes: [
      "A) Método para evitar paradas e falhas nas máquinas",
      "B) Processo de aumentar a produção",
      "C) Técnica de treinamento de operadores",
      "D) Sistema para eliminar resíduos",
    ],
    resposta: 0,
  },
  {
    questao: "O que fazer com uma máquina danificada?",
    imagem: "imgs\\questao21.svg",
    opcoes: [
      "A) Parar e reparar imediatamente",
      "B) Continuar usando até a próxima pausa",
      "C) Ajustar manualmente o processo",
      "D) Notificar apenas ao final do turno",
    ],
    resposta: 0,
  },
  {
    questao: "Como saber quando trocar uma ferramenta usada?",
    imagem: "imgs\\questao22.svg",
    opcoes: [
      "A) Como saber quando trocar uma ferramenta usada?",
      "B) Ao final do turno",
      "C) Somente quando a produção é interrompida",
      "D) A cada 100 horas de uso",
    ],
    resposta: 0,
  },

  {
    questao: "Por que é importante marcar a vida útil das ferramentas?",
    imagem: "imgs\\questao23.svg",
    opcoes: [
      "A) Para prevenir falhas na produção",
      "B) Para reduzir o consumo de energia",
      "C) Para aumentar o estoque de ferramentas",
      "D) Para simplificar a manutenção",
    ],
    resposta: 0,
  },
  {
    questao: "Como os produtos são identificados na fábrica?",
    imagem: "imgs\\questao24.svg",
    opcoes: [
      "A) Por etiquetas com códigos e status",
      "B) Por ordem de chegada",
      "C) Pela cor do produto",
      "D) Pela quantidade produzida",
    ],
    resposta: 0,
  },
  {
    questao: "O que é o 'refugo' e como ele é descartado?",
    imagem: "imgs\\questao25.svg",
    opcoes: [
      "A) Produtos sem uso, descartados de forma segura",
      "B) Produtos em bom estado, mas fora do padrão",
      "C) Produtos retidos para verificação",
      "D) Materiais prontos para venda",
    ],
    resposta: 0,
  },
  {
    questao: "O que fazer com um produto que caiu no chão?",
    imagem: "imgs\\questao26.svg",
    opcoes: [
      "A) Recolher e mandar para o retrabalho",
      "B) Colocar de volta na linha de produção",
      "C) Jogar fora, conforme procedimento",
      "D) Verificar com o gerente o que fazer",
    ],
    resposta: 2,
  },
  // EU PAREI AQUI!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  // Depois que eu fizer todas as imagens, eu vou colocar o caminho delas
  {
    questao: "Por que reportar reincidências de produtos caídos?",
    imagem: "imgs\\questao27.svg",
    opcoes: [
      "A) Para identificar e corrigir causas de falhas",
      "B) Para aumentar a velocidade do processo",
      "C) Para melhorar a organização da fábrica",
      "D) Para promover mudanças nos turnos",
    ],
    resposta: 0,
  },
  {
    questao: "O que é o método 'First In, First Out' (FIFO)?",
    imagem: "imgs\\questao28.svg",
    opcoes: [
      "A) A ordem de produtos mais novos para mais velhos",
      "B) A ordem de saída é a mesma da entrada",
      "C) A prioridade é para os produtos mais recentes",
      "D) A produção de maior qualidade tem prioridade",
    ],
    resposta: 1,
  },
  {
    questao: "O que deve ser feito ao reiniciar uma máquina após pausa?",
    imagem: "imgs\\questao29.svg",
    opcoes: [
      "A) Iniciar imediatamente o processo",
      "B) Verificar e seguir o padrão definido de reinício",
      "C) Esperar até que o supervisor esteja presente",
      "D) Reiniciar com a produção em alta velocidade",
    ],
    resposta: 1,
  },
  {
    questao: "Como lidar com um produto que precisa de retrabalho?",
    imagem: "imgs\\questao30.svg",
    opcoes: [
      "A) Seguir o procedimento de retrabalho e usar equipamentos aprovados",
      "B) Enviar diretamente para o cliente",
      "C) Guardar em uma área separada para inspeção",
      "D) Manter no processo sem mudanças",
    ],
    resposta: 0,
  },
  {
    questao: "Como garantir que só a peça correta seja usada na montagem?",
    imagem: "imgs\\questao31.svg",
    opcoes: [
      "A) Deixar todas as peças acessíveis ao operador",
      "B) Separar e identificar claramente a peça correta",
      "C) Rotacionar as peças periodicamente",
      "D) Permitir que o operador escolha a peça",
    ],
    resposta: 1,
  },
  {
    questao: "Como evitar que componentes errados sejam usados juntos?",
    imagem: "imgs\\questao32.svg",
    opcoes: [
      "A) Usar containers fechados para as peças",
      "B) Deixar todas as peças misturadas para acesso rápido",
      "C) Desconsiderar a verificação de componentes",
      "D) Armazenar todos os componentes juntos",
    ],
    resposta: 0,
  },
  {
    questao: "O que fazer com sobras de material após a produção?",
    imagem: "imgs\\questao33.svg",
    opcoes: [
      "A) Dispensar imediatamente",
      "B) Guardar e identificar claramente as sobras",
      "C) Usar em qualquer produção subsequente",
      "D) Armazenar sem identificação para economia de tempo",
    ],
    resposta: 1,
  },
  {
    questao: "Como identificar um produto que está sem etiqueta?",
    imagem: "imgs\\questao34.svg",
    opcoes: [
      "A) Deixar no fluxo de produção para análise posterior",
      "B) Identificar manualmente como retrabalho ou refugo",
      "C) Colocar de volta no processo de montagem",
      "D) Ignorar e enviar ao cliente",
    ],
    resposta: 1,
  },
  {
    questao: "Como descartar materiais rejeitados?",
    imagem: "imgs\\questao35.svg",
    opcoes: [
      "A) Armazenar para uma possível reutilização",
      "B) Descartar conforme procedimento e impedir reutilização",
      "C) Enviar para áreas de refugo não especificadas",
      "D) Utilizar novamente na produção com ajustes",
    ],
    resposta: 1,
  },
  {
    questao: "Como a temperatura afeta o processo de fabricação?",
    imagem: "imgs\\questao36.svg",
    opcoes: [
      "A) Aumenta a velocidade do processo",
      "B) Afeta a qualidade do produto final",
      "C) Não tem influência na produção",
      "D) Aumenta os custos de produção",
    ],
    resposta: 1,
  },
  {
    questao: "Por que participar das instruções de segurança é importante?",
    imagem: "imgs\\questao37.svg",
    opcoes: [
      "A) Para cumprir exigências de auditoria",
      "B) Para garantir a segurança e qualidade no trabalho",
      "C) Para marcar presença e cumprir o horário",
      "D) Para manter o ritmo de produção elevado",
    ],
    resposta: 1,
  },
  {
    questao: "Como a organização afeta a qualidade e eficiência?",
    imagem: "imgs\\questao38.svg",
    opcoes: [
      "A) Facilita a localização de problemas e previne erros",
      "B) Reduz o número de funcionários",
      "C) Aumenta a quantidade de produtos defeituosos",
      "D) Aumenta o custo de produção",
    ],
    resposta: 0,
  },
  {
    questao: "Como a qualidade impacta o cliente final?",
    imagem: "imgs\\questao39.svg",
    opcoes: [
      "A) Aumenta o custo para o cliente",
      "B) Melhora a satisfação e confiança do cliente",
      "C) Aumenta o tempo de entrega",
      "D) Reduz a durabilidade do produto",
    ],
    resposta: 1,
  },
  {
    questao: "Qual Q corresponde à imagem?",
    imagem: "imgs\\questao40.jpeg",
    opcoes: [
      "A) 3Q",
      "B) Isso não se encaixa nos 14Q",
      "C) 12Q",
      "D) Corresponde ao processo de envio das peças",
    ],
    resposta: 2,
  },
];
